Branch delete medicine
AY2122S2-CS2113T-T09-3/tp pull request #45
Opened 2022-03-15 12:33 UTC by shxr3f

Implemented methods that allows user to delete medicines from the records. (Resolves #16)
Also tried out some junit testing on the Parser Class methods! Please take a look at my code!

2022-03-15 13:49 UTC, tanweili approved these changes
Okay to merge on my end

2022-03-15 14:29 UTC, kktai1512 requested changes

2022-03-15 14:29 UTC, kktai1512 commented on src/main/java/seedu/duke/assets/MedicineList.java
> +    public int size() {
maybe getSize would be a better name considering its a method?

2022-03-15 14:29 UTC, kktai1512 commented on src/main/java/seedu/duke/helper/Command.java
> +    public void deleteMedicine(MedicineList medicineList, String stringIndex) {
is the actual deleting not included?

should be calling medicineList.delete bla bla right

2022-03-15 15:07 UTC, shxr3f commented on src/main/java/seedu/duke/helper/Command.java
> +    public void deleteMedicine(MedicineList medicineList, String stringIndex) {
I think you missed it, its present on line 81.

2022-03-15 16:43 UTC, Anvitha-r commented
looks good can be merged and closed!

2022-03-16 01:49 UTC, shxr3f commented
Thanks for the reviews guys, I'll be merging the PR then, since there aren't any issues!

2022-03-16 01:49 UTC, merged